language: node_js
node_js:
  - 11
script:
  - npm run lint
  - npm run test:unit
before_deploy:
  - npm run build
after_success:
  - npm install -g codecov
  - codecov -f test/unit/coverage/lcov.info
